#ifndef GroupID_h
#define GroupID_h

enum class GroupID {
    MAIN,
    AWARENESS_RECORD,
    POSTURE_MAIN,
    POSTURE_ADJUST,
    POSTURE_HOLD,
    POSTURE_COMPLETE,
    AFFIRMATION_MAIN,
    POWER_MASSAGE_MAIN,
    INTUITION_MAIN,
    BREATHING_MAIN,
    BREATHING_EXERCISE,
    BREATHING_COMPLETE,
    MORE_MAIN,
    MORE_SETTINGS,
    MORE_INFO
};

#endif