#include "images.h"

const ext_img_desc_t images[41] = {
    { "background", &img_background },
    { "absolute-freedom", &img_absolute_freedom },
    { "affirmation-button", &img_affirmation_button },
    { "affirmation-button-highlight", &img_affirmation_button_highlight },
    { "affirmation-logo", &img_affirmation_logo },
    { "awareness-button", &img_awareness_button },
    { "awareness-button-highlight", &img_awareness_button_highlight },
    { "awareness-logo", &img_awareness_logo },
    { "back-button", &img_back_button },
    { "battery", &img_battery },
    { "breathing-exit-demo", &img_breathing_exit_demo },
    { "breathing-prep-1-demo", &img_breathing_prep_1_demo },
    { "breathing-techniques-button", &img_breathing_techniques_button },
    { "breathing-techniques-button-highlight", &img_breathing_techniques_button_highlight },
    { "breathing-techniques-logo", &img_breathing_techniques_logo },
    { "brightness-icon-bright", &img_brightness_icon_bright },
    { "brightness-icon-dark", &img_brightness_icon_dark },
    { "button-next", &img_button_next },
    { "button-no", &img_button_no },
    { "button-preparation-info", &img_button_preparation_info },
    { "button-yes", &img_button_yes },
    { "more-button", &img_more_button },
    { "more-button-highlight", &img_more_button_highlight },
    { "more-icon", &img_more_icon },
    { "more-logo", &img_more_logo },
    { "posture-button", &img_posture_button },
    { "posture-button-highlight", &img_posture_button_highlight },
    { "posture-logo", &img_posture_logo },
    { "power-massage-button", &img_power_massage_button },
    { "power-massage-button-highlight", &img_power_massage_button_highlight },
    { "power-massage-logo", &img_power_massage_logo },
    { "primary-button", &img_primary_button },
    { "settings-brightness-button", &img_settings_brightness_button },
    { "settings-brightness-header", &img_settings_brightness_header },
    { "settings-language-button", &img_settings_language_button },
    { "settings-text", &img_settings_text },
    { "slider-background", &img_slider_background },
    { "slider-background-full", &img_slider_background_full },
    { "slider-indicator", &img_slider_indicator },
    { "strengthen-intuition-button", &img_strengthen_intuition_button },
    { "subconscious-thoughts-button", &img_subconscious_thoughts_button },
};
